<?php


/**
 * This class defines the structure of the 'order_shipping_options' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/15/11 12:03:05
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class OrderShippingOptionsTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.OrderShippingOptionsTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('order_shipping_options');
		$this->setPhpName('OrderShippingOptions');
		$this->setClassname('OrderShippingOptions');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('ORDER_ID', 'OrderId', 'INTEGER' , 'order_shipping', 'ID', true, null, null);
		$this->addForeignPrimaryKey('OPTION_ID', 'OptionId', 'INTEGER' , 'shipping_options', 'ID', true, null, null);
		$this->addColumn('OPTION_VALUE', 'OptionValue', 'VARCHAR', false, 255, null);
		$this->addColumn('OPTION_PRICE', 'OptionPrice', 'DECIMAL', false, 10, null);
		$this->addColumn('AMOUNT', 'Amount', 'DECIMAL', false, 10, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('OrderShipping', 'OrderShipping', RelationMap::MANY_TO_ONE, array('order_id' => 'id', ), null, null);
    $this->addRelation('ShippingOptions', 'ShippingOptions', RelationMap::MANY_TO_ONE, array('option_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // OrderShippingOptionsTableMap
