<?php

/**
 * Base class that represents a row from the 'shipping_prices' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Oct 18 23:48:17 2010
 *
 * @package    lib.model.om
 */
abstract class BaseShippingPrices extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ShippingPricesPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the courier_id field.
	 * @var        int
	 */
	protected $courier_id;

	/**
	 * The value for the product_id field.
	 * @var        int
	 */
	protected $product_id;

	/**
	 * The value for the service_id field.
	 * @var        string
	 */
	protected $service_id;

	/**
	 * The value for the price field.
	 * @var        string
	 */
	protected $price;

	/**
	 * The value for the prom_price field.
	 * @var        string
	 */
	protected $prom_price;

	/**
	 * The value for the is_dynamic_price field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_dynamic_price;

	/**
	 * The value for the dynamic_price field.
	 * @var        string
	 */
	protected $dynamic_price;

	/**
	 * The value for the dynamic_price_what_if field.
	 * Note: this column has a database default value of: '50.00'
	 * @var        string
	 */
	protected $dynamic_price_what_if;

	/**
	 * The value for the show field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $show;

	/**
	 * The value for the is_default field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_default;

	/**
	 * The value for the is_prom field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_prom;

	/**
	 * The value for the is_available field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $is_available;

	/**
	 * The value for the notice field.
	 * @var        string
	 */
	protected $notice;

	/**
	 * @var        Courier
	 */
	protected $aCourier;

	/**
	 * @var        ShippingProducts
	 */
	protected $aShippingProducts;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ShippingPricesPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_dynamic_price = false;
		$this->dynamic_price_what_if = '50.00';
		$this->show = true;
		$this->is_default = false;
		$this->is_prom = false;
		$this->is_available = true;
	}

	/**
	 * Initializes internal state of BaseShippingPrices object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [courier_id] column value.
	 * 
	 * @return     int
	 */
	public function getCourierId()
	{
		return $this->courier_id;
	}

	/**
	 * Get the [product_id] column value.
	 * 
	 * @return     int
	 */
	public function getProductId()
	{
		return $this->product_id;
	}

	/**
	 * Get the [service_id] column value.
	 * 
	 * @return     string
	 */
	public function getServiceId()
	{
		return $this->service_id;
	}

	/**
	 * Get the [price] column value.
	 * 
	 * @return     string
	 */
	public function getPrice()
	{
		return $this->price;
	}

	/**
	 * Get the [prom_price] column value.
	 * 
	 * @return     string
	 */
	public function getPromPrice()
	{
		return $this->prom_price;
	}

	/**
	 * Get the [is_dynamic_price] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsDynamicPrice()
	{
		return $this->is_dynamic_price;
	}

	/**
	 * Get the [dynamic_price] column value.
	 * 
	 * @return     string
	 */
	public function getDynamicPrice()
	{
		return $this->dynamic_price;
	}

	/**
	 * Get the [dynamic_price_what_if] column value.
	 * 
	 * @return     string
	 */
	public function getDynamicPriceWhatIf()
	{
		return $this->dynamic_price_what_if;
	}

	/**
	 * Get the [show] column value.
	 * 
	 * @return     boolean
	 */
	public function getShow()
	{
		return $this->show;
	}

	/**
	 * Get the [is_default] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsDefault()
	{
		return $this->is_default;
	}

	/**
	 * Get the [is_prom] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsProm()
	{
		return $this->is_prom;
	}

	/**
	 * Get the [is_available] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsAvailable()
	{
		return $this->is_available;
	}

	/**
	 * Get the [notice] column value.
	 * 
	 * @return     string
	 */
	public function getNotice()
	{
		return $this->notice;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [courier_id] column.
	 * 
	 * @param      int $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setCourierId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->courier_id !== $v) {
			$this->courier_id = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::COURIER_ID;
		}

		if ($this->aCourier !== null && $this->aCourier->getId() !== $v) {
			$this->aCourier = null;
		}

		return $this;
	} // setCourierId()

	/**
	 * Set the value of [product_id] column.
	 * 
	 * @param      int $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setProductId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->product_id !== $v) {
			$this->product_id = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::PRODUCT_ID;
		}

		if ($this->aShippingProducts !== null && $this->aShippingProducts->getId() !== $v) {
			$this->aShippingProducts = null;
		}

		return $this;
	} // setProductId()

	/**
	 * Set the value of [service_id] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setServiceId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->service_id !== $v) {
			$this->service_id = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::SERVICE_ID;
		}

		return $this;
	} // setServiceId()

	/**
	 * Set the value of [price] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->price !== $v) {
			$this->price = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::PRICE;
		}

		return $this;
	} // setPrice()

	/**
	 * Set the value of [prom_price] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setPromPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->prom_price !== $v) {
			$this->prom_price = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::PROM_PRICE;
		}

		return $this;
	} // setPromPrice()

	/**
	 * Set the value of [is_dynamic_price] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setIsDynamicPrice($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_dynamic_price !== $v || $this->isNew()) {
			$this->is_dynamic_price = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::IS_DYNAMIC_PRICE;
		}

		return $this;
	} // setIsDynamicPrice()

	/**
	 * Set the value of [dynamic_price] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setDynamicPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dynamic_price !== $v) {
			$this->dynamic_price = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::DYNAMIC_PRICE;
		}

		return $this;
	} // setDynamicPrice()

	/**
	 * Set the value of [dynamic_price_what_if] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setDynamicPriceWhatIf($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dynamic_price_what_if !== $v || $this->isNew()) {
			$this->dynamic_price_what_if = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::DYNAMIC_PRICE_WHAT_IF;
		}

		return $this;
	} // setDynamicPriceWhatIf()

	/**
	 * Set the value of [show] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setShow($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->show !== $v || $this->isNew()) {
			$this->show = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::SHOW;
		}

		return $this;
	} // setShow()

	/**
	 * Set the value of [is_default] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setIsDefault($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_default !== $v || $this->isNew()) {
			$this->is_default = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::IS_DEFAULT;
		}

		return $this;
	} // setIsDefault()

	/**
	 * Set the value of [is_prom] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setIsProm($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_prom !== $v || $this->isNew()) {
			$this->is_prom = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::IS_PROM;
		}

		return $this;
	} // setIsProm()

	/**
	 * Set the value of [is_available] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setIsAvailable($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_available !== $v || $this->isNew()) {
			$this->is_available = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::IS_AVAILABLE;
		}

		return $this;
	} // setIsAvailable()

	/**
	 * Set the value of [notice] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingPrices The current object (for fluent API support)
	 */
	public function setNotice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->notice !== $v) {
			$this->notice = $v;
			$this->modifiedColumns[] = ShippingPricesPeer::NOTICE;
		}

		return $this;
	} // setNotice()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->is_dynamic_price !== false) {
				return false;
			}

			if ($this->dynamic_price_what_if !== '50.00') {
				return false;
			}

			if ($this->show !== true) {
				return false;
			}

			if ($this->is_default !== false) {
				return false;
			}

			if ($this->is_prom !== false) {
				return false;
			}

			if ($this->is_available !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->courier_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->product_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->service_id = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->price = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->prom_price = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->is_dynamic_price = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->dynamic_price = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->dynamic_price_what_if = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->show = ($row[$startcol + 9] !== null) ? (boolean) $row[$startcol + 9] : null;
			$this->is_default = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->is_prom = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->is_available = ($row[$startcol + 12] !== null) ? (boolean) $row[$startcol + 12] : null;
			$this->notice = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = ShippingPricesPeer::NUM_COLUMNS - ShippingPricesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ShippingPrices object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCourier !== null && $this->courier_id !== $this->aCourier->getId()) {
			$this->aCourier = null;
		}
		if ($this->aShippingProducts !== null && $this->product_id !== $this->aShippingProducts->getId()) {
			$this->aShippingProducts = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShippingPricesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ShippingPricesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCourier = null;
			$this->aShippingProducts = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShippingPricesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseShippingPrices:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ShippingPricesPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseShippingPrices:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShippingPricesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseShippingPrices:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseShippingPrices:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ShippingPricesPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCourier !== null) {
				if ($this->aCourier->isModified() || $this->aCourier->isNew()) {
					$affectedRows += $this->aCourier->save($con);
				}
				$this->setCourier($this->aCourier);
			}

			if ($this->aShippingProducts !== null) {
				if ($this->aShippingProducts->isModified() || $this->aShippingProducts->isNew()) {
					$affectedRows += $this->aShippingProducts->save($con);
				}
				$this->setShippingProducts($this->aShippingProducts);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ShippingPricesPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ShippingPricesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ShippingPricesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCourier !== null) {
				if (!$this->aCourier->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCourier->getValidationFailures());
				}
			}

			if ($this->aShippingProducts !== null) {
				if (!$this->aShippingProducts->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aShippingProducts->getValidationFailures());
				}
			}


			if (($retval = ShippingPricesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ShippingPricesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCourierId();
				break;
			case 2:
				return $this->getProductId();
				break;
			case 3:
				return $this->getServiceId();
				break;
			case 4:
				return $this->getPrice();
				break;
			case 5:
				return $this->getPromPrice();
				break;
			case 6:
				return $this->getIsDynamicPrice();
				break;
			case 7:
				return $this->getDynamicPrice();
				break;
			case 8:
				return $this->getDynamicPriceWhatIf();
				break;
			case 9:
				return $this->getShow();
				break;
			case 10:
				return $this->getIsDefault();
				break;
			case 11:
				return $this->getIsProm();
				break;
			case 12:
				return $this->getIsAvailable();
				break;
			case 13:
				return $this->getNotice();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ShippingPricesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCourierId(),
			$keys[2] => $this->getProductId(),
			$keys[3] => $this->getServiceId(),
			$keys[4] => $this->getPrice(),
			$keys[5] => $this->getPromPrice(),
			$keys[6] => $this->getIsDynamicPrice(),
			$keys[7] => $this->getDynamicPrice(),
			$keys[8] => $this->getDynamicPriceWhatIf(),
			$keys[9] => $this->getShow(),
			$keys[10] => $this->getIsDefault(),
			$keys[11] => $this->getIsProm(),
			$keys[12] => $this->getIsAvailable(),
			$keys[13] => $this->getNotice(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ShippingPricesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCourierId($value);
				break;
			case 2:
				$this->setProductId($value);
				break;
			case 3:
				$this->setServiceId($value);
				break;
			case 4:
				$this->setPrice($value);
				break;
			case 5:
				$this->setPromPrice($value);
				break;
			case 6:
				$this->setIsDynamicPrice($value);
				break;
			case 7:
				$this->setDynamicPrice($value);
				break;
			case 8:
				$this->setDynamicPriceWhatIf($value);
				break;
			case 9:
				$this->setShow($value);
				break;
			case 10:
				$this->setIsDefault($value);
				break;
			case 11:
				$this->setIsProm($value);
				break;
			case 12:
				$this->setIsAvailable($value);
				break;
			case 13:
				$this->setNotice($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ShippingPricesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCourierId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setProductId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setServiceId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPrice($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPromPrice($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setIsDynamicPrice($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDynamicPrice($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDynamicPriceWhatIf($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setShow($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setIsDefault($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setIsProm($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setIsAvailable($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setNotice($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ShippingPricesPeer::DATABASE_NAME);

		if ($this->isColumnModified(ShippingPricesPeer::ID)) $criteria->add(ShippingPricesPeer::ID, $this->id);
		if ($this->isColumnModified(ShippingPricesPeer::COURIER_ID)) $criteria->add(ShippingPricesPeer::COURIER_ID, $this->courier_id);
		if ($this->isColumnModified(ShippingPricesPeer::PRODUCT_ID)) $criteria->add(ShippingPricesPeer::PRODUCT_ID, $this->product_id);
		if ($this->isColumnModified(ShippingPricesPeer::SERVICE_ID)) $criteria->add(ShippingPricesPeer::SERVICE_ID, $this->service_id);
		if ($this->isColumnModified(ShippingPricesPeer::PRICE)) $criteria->add(ShippingPricesPeer::PRICE, $this->price);
		if ($this->isColumnModified(ShippingPricesPeer::PROM_PRICE)) $criteria->add(ShippingPricesPeer::PROM_PRICE, $this->prom_price);
		if ($this->isColumnModified(ShippingPricesPeer::IS_DYNAMIC_PRICE)) $criteria->add(ShippingPricesPeer::IS_DYNAMIC_PRICE, $this->is_dynamic_price);
		if ($this->isColumnModified(ShippingPricesPeer::DYNAMIC_PRICE)) $criteria->add(ShippingPricesPeer::DYNAMIC_PRICE, $this->dynamic_price);
		if ($this->isColumnModified(ShippingPricesPeer::DYNAMIC_PRICE_WHAT_IF)) $criteria->add(ShippingPricesPeer::DYNAMIC_PRICE_WHAT_IF, $this->dynamic_price_what_if);
		if ($this->isColumnModified(ShippingPricesPeer::SHOW)) $criteria->add(ShippingPricesPeer::SHOW, $this->show);
		if ($this->isColumnModified(ShippingPricesPeer::IS_DEFAULT)) $criteria->add(ShippingPricesPeer::IS_DEFAULT, $this->is_default);
		if ($this->isColumnModified(ShippingPricesPeer::IS_PROM)) $criteria->add(ShippingPricesPeer::IS_PROM, $this->is_prom);
		if ($this->isColumnModified(ShippingPricesPeer::IS_AVAILABLE)) $criteria->add(ShippingPricesPeer::IS_AVAILABLE, $this->is_available);
		if ($this->isColumnModified(ShippingPricesPeer::NOTICE)) $criteria->add(ShippingPricesPeer::NOTICE, $this->notice);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ShippingPricesPeer::DATABASE_NAME);

		$criteria->add(ShippingPricesPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ShippingPrices (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCourierId($this->courier_id);

		$copyObj->setProductId($this->product_id);

		$copyObj->setServiceId($this->service_id);

		$copyObj->setPrice($this->price);

		$copyObj->setPromPrice($this->prom_price);

		$copyObj->setIsDynamicPrice($this->is_dynamic_price);

		$copyObj->setDynamicPrice($this->dynamic_price);

		$copyObj->setDynamicPriceWhatIf($this->dynamic_price_what_if);

		$copyObj->setShow($this->show);

		$copyObj->setIsDefault($this->is_default);

		$copyObj->setIsProm($this->is_prom);

		$copyObj->setIsAvailable($this->is_available);

		$copyObj->setNotice($this->notice);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ShippingPrices Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ShippingPricesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ShippingPricesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Courier object.
	 *
	 * @param      Courier $v
	 * @return     ShippingPrices The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCourier(Courier $v = null)
	{
		if ($v === null) {
			$this->setCourierId(NULL);
		} else {
			$this->setCourierId($v->getId());
		}

		$this->aCourier = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Courier object, it will not be re-added.
		if ($v !== null) {
			$v->addShippingPrices($this);
		}

		return $this;
	}


	/**
	 * Get the associated Courier object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Courier The associated Courier object.
	 * @throws     PropelException
	 */
	public function getCourier(PropelPDO $con = null)
	{
		if ($this->aCourier === null && ($this->courier_id !== null)) {
			$this->aCourier = CourierPeer::retrieveByPk($this->courier_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCourier->addShippingPricess($this);
			 */
		}
		return $this->aCourier;
	}

	/**
	 * Declares an association between this object and a ShippingProducts object.
	 *
	 * @param      ShippingProducts $v
	 * @return     ShippingPrices The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setShippingProducts(ShippingProducts $v = null)
	{
		if ($v === null) {
			$this->setProductId(NULL);
		} else {
			$this->setProductId($v->getId());
		}

		$this->aShippingProducts = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ShippingProducts object, it will not be re-added.
		if ($v !== null) {
			$v->addShippingPrices($this);
		}

		return $this;
	}


	/**
	 * Get the associated ShippingProducts object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ShippingProducts The associated ShippingProducts object.
	 * @throws     PropelException
	 */
	public function getShippingProducts(PropelPDO $con = null)
	{
		if ($this->aShippingProducts === null && ($this->product_id !== null)) {
			$this->aShippingProducts = ShippingProductsPeer::retrieveByPk($this->product_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aShippingProducts->addShippingPricess($this);
			 */
		}
		return $this->aShippingProducts;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aCourier = null;
			$this->aShippingProducts = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseShippingPrices:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseShippingPrices::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseShippingPrices
