<?php

/**
 * Base class that represents a row from the 'shipping_types_prices' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/19/10 22:00:55
 *
 * @package    lib.model.om
 */
abstract class BaseShippingTypesPrices extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ShippingTypesPricesPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the type_id field.
	 * @var        int
	 */
	protected $type_id;

	/**
	 * The value for the packaging_type_id field.
	 * @var        int
	 */
	protected $packaging_type_id;

	/**
	 * The value for the price field.
	 * @var        string
	 */
	protected $price;

	/**
	 * The value for the initial_weight field.
	 * @var        string
	 */
	protected $initial_weight;

	/**
	 * The value for the final_weight field.
	 * @var        string
	 */
	protected $final_weight;

	/**
	 * The value for the is_prom field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_prom;

	/**
	 * The value for the prom_price field.
	 * @var        string
	 */
	protected $prom_price;

	/**
	 * The value for the is_dynamic_price field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_dynamic_price;

	/**
	 * The value for the dynamic_price field.
	 * @var        string
	 */
	protected $dynamic_price;

	/**
	 * The value for the dynamic_price_what_if field.
	 * Note: this column has a database default value of: '50.00'
	 * @var        string
	 */
	protected $dynamic_price_what_if;

	/**
	 * The value for the show field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $show;

	/**
	 * The value for the is_available field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $is_available;

	/**
	 * The value for the notice field.
	 * @var        string
	 */
	protected $notice;

	/**
	 * @var        ShippingTypes
	 */
	protected $aShippingTypes;

	/**
	 * @var        PackagingTypes
	 */
	protected $aPackagingTypes;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ShippingTypesPricesPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_prom = false;
		$this->is_dynamic_price = false;
		$this->dynamic_price_what_if = '50.00';
		$this->show = true;
		$this->is_available = true;
	}

	/**
	 * Initializes internal state of BaseShippingTypesPrices object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [type_id] column value.
	 * 
	 * @return     int
	 */
	public function getTypeId()
	{
		return $this->type_id;
	}

	/**
	 * Get the [packaging_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getPackagingTypeId()
	{
		return $this->packaging_type_id;
	}

	/**
	 * Get the [price] column value.
	 * 
	 * @return     string
	 */
	public function getPrice()
	{
		return $this->price;
	}

	/**
	 * Get the [initial_weight] column value.
	 * 
	 * @return     string
	 */
	public function getInitialWeight()
	{
		return $this->initial_weight;
	}

	/**
	 * Get the [final_weight] column value.
	 * 
	 * @return     string
	 */
	public function getFinalWeight()
	{
		return $this->final_weight;
	}

	/**
	 * Get the [is_prom] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsProm()
	{
		return $this->is_prom;
	}

	/**
	 * Get the [prom_price] column value.
	 * 
	 * @return     string
	 */
	public function getPromPrice()
	{
		return $this->prom_price;
	}

	/**
	 * Get the [is_dynamic_price] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsDynamicPrice()
	{
		return $this->is_dynamic_price;
	}

	/**
	 * Get the [dynamic_price] column value.
	 * 
	 * @return     string
	 */
	public function getDynamicPrice()
	{
		return $this->dynamic_price;
	}

	/**
	 * Get the [dynamic_price_what_if] column value.
	 * 
	 * @return     string
	 */
	public function getDynamicPriceWhatIf()
	{
		return $this->dynamic_price_what_if;
	}

	/**
	 * Get the [show] column value.
	 * 
	 * @return     boolean
	 */
	public function getShow()
	{
		return $this->show;
	}

	/**
	 * Get the [is_available] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsAvailable()
	{
		return $this->is_available;
	}

	/**
	 * Get the [notice] column value.
	 * 
	 * @return     string
	 */
	public function getNotice()
	{
		return $this->notice;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->type_id !== $v) {
			$this->type_id = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::TYPE_ID;
		}

		if ($this->aShippingTypes !== null && $this->aShippingTypes->getId() !== $v) {
			$this->aShippingTypes = null;
		}

		return $this;
	} // setTypeId()

	/**
	 * Set the value of [packaging_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setPackagingTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->packaging_type_id !== $v) {
			$this->packaging_type_id = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::PACKAGING_TYPE_ID;
		}

		if ($this->aPackagingTypes !== null && $this->aPackagingTypes->getId() !== $v) {
			$this->aPackagingTypes = null;
		}

		return $this;
	} // setPackagingTypeId()

	/**
	 * Set the value of [price] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->price !== $v) {
			$this->price = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::PRICE;
		}

		return $this;
	} // setPrice()

	/**
	 * Set the value of [initial_weight] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setInitialWeight($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->initial_weight !== $v) {
			$this->initial_weight = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::INITIAL_WEIGHT;
		}

		return $this;
	} // setInitialWeight()

	/**
	 * Set the value of [final_weight] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setFinalWeight($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->final_weight !== $v) {
			$this->final_weight = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::FINAL_WEIGHT;
		}

		return $this;
	} // setFinalWeight()

	/**
	 * Set the value of [is_prom] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setIsProm($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_prom !== $v || $this->isNew()) {
			$this->is_prom = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::IS_PROM;
		}

		return $this;
	} // setIsProm()

	/**
	 * Set the value of [prom_price] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setPromPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->prom_price !== $v) {
			$this->prom_price = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::PROM_PRICE;
		}

		return $this;
	} // setPromPrice()

	/**
	 * Set the value of [is_dynamic_price] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setIsDynamicPrice($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_dynamic_price !== $v || $this->isNew()) {
			$this->is_dynamic_price = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::IS_DYNAMIC_PRICE;
		}

		return $this;
	} // setIsDynamicPrice()

	/**
	 * Set the value of [dynamic_price] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setDynamicPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dynamic_price !== $v) {
			$this->dynamic_price = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::DYNAMIC_PRICE;
		}

		return $this;
	} // setDynamicPrice()

	/**
	 * Set the value of [dynamic_price_what_if] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setDynamicPriceWhatIf($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dynamic_price_what_if !== $v || $this->isNew()) {
			$this->dynamic_price_what_if = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::DYNAMIC_PRICE_WHAT_IF;
		}

		return $this;
	} // setDynamicPriceWhatIf()

	/**
	 * Set the value of [show] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setShow($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->show !== $v || $this->isNew()) {
			$this->show = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::SHOW;
		}

		return $this;
	} // setShow()

	/**
	 * Set the value of [is_available] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setIsAvailable($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_available !== $v || $this->isNew()) {
			$this->is_available = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::IS_AVAILABLE;
		}

		return $this;
	} // setIsAvailable()

	/**
	 * Set the value of [notice] column.
	 * 
	 * @param      string $v new value
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 */
	public function setNotice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->notice !== $v) {
			$this->notice = $v;
			$this->modifiedColumns[] = ShippingTypesPricesPeer::NOTICE;
		}

		return $this;
	} // setNotice()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->is_prom !== false) {
				return false;
			}

			if ($this->is_dynamic_price !== false) {
				return false;
			}

			if ($this->dynamic_price_what_if !== '50.00') {
				return false;
			}

			if ($this->show !== true) {
				return false;
			}

			if ($this->is_available !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->type_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->packaging_type_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->price = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->initial_weight = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->final_weight = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->is_prom = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->prom_price = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->is_dynamic_price = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
			$this->dynamic_price = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->dynamic_price_what_if = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->show = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->is_available = ($row[$startcol + 12] !== null) ? (boolean) $row[$startcol + 12] : null;
			$this->notice = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = ShippingTypesPricesPeer::NUM_COLUMNS - ShippingTypesPricesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ShippingTypesPrices object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aShippingTypes !== null && $this->type_id !== $this->aShippingTypes->getId()) {
			$this->aShippingTypes = null;
		}
		if ($this->aPackagingTypes !== null && $this->packaging_type_id !== $this->aPackagingTypes->getId()) {
			$this->aPackagingTypes = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShippingTypesPricesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ShippingTypesPricesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aShippingTypes = null;
			$this->aPackagingTypes = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShippingTypesPricesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseShippingTypesPrices:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ShippingTypesPricesPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseShippingTypesPrices:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShippingTypesPricesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseShippingTypesPrices:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseShippingTypesPrices:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ShippingTypesPricesPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aShippingTypes !== null) {
				if ($this->aShippingTypes->isModified() || $this->aShippingTypes->isNew()) {
					$affectedRows += $this->aShippingTypes->save($con);
				}
				$this->setShippingTypes($this->aShippingTypes);
			}

			if ($this->aPackagingTypes !== null) {
				if ($this->aPackagingTypes->isModified() || $this->aPackagingTypes->isNew()) {
					$affectedRows += $this->aPackagingTypes->save($con);
				}
				$this->setPackagingTypes($this->aPackagingTypes);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ShippingTypesPricesPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ShippingTypesPricesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ShippingTypesPricesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aShippingTypes !== null) {
				if (!$this->aShippingTypes->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aShippingTypes->getValidationFailures());
				}
			}

			if ($this->aPackagingTypes !== null) {
				if (!$this->aPackagingTypes->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPackagingTypes->getValidationFailures());
				}
			}


			if (($retval = ShippingTypesPricesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ShippingTypesPricesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTypeId();
				break;
			case 2:
				return $this->getPackagingTypeId();
				break;
			case 3:
				return $this->getPrice();
				break;
			case 4:
				return $this->getInitialWeight();
				break;
			case 5:
				return $this->getFinalWeight();
				break;
			case 6:
				return $this->getIsProm();
				break;
			case 7:
				return $this->getPromPrice();
				break;
			case 8:
				return $this->getIsDynamicPrice();
				break;
			case 9:
				return $this->getDynamicPrice();
				break;
			case 10:
				return $this->getDynamicPriceWhatIf();
				break;
			case 11:
				return $this->getShow();
				break;
			case 12:
				return $this->getIsAvailable();
				break;
			case 13:
				return $this->getNotice();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ShippingTypesPricesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTypeId(),
			$keys[2] => $this->getPackagingTypeId(),
			$keys[3] => $this->getPrice(),
			$keys[4] => $this->getInitialWeight(),
			$keys[5] => $this->getFinalWeight(),
			$keys[6] => $this->getIsProm(),
			$keys[7] => $this->getPromPrice(),
			$keys[8] => $this->getIsDynamicPrice(),
			$keys[9] => $this->getDynamicPrice(),
			$keys[10] => $this->getDynamicPriceWhatIf(),
			$keys[11] => $this->getShow(),
			$keys[12] => $this->getIsAvailable(),
			$keys[13] => $this->getNotice(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ShippingTypesPricesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTypeId($value);
				break;
			case 2:
				$this->setPackagingTypeId($value);
				break;
			case 3:
				$this->setPrice($value);
				break;
			case 4:
				$this->setInitialWeight($value);
				break;
			case 5:
				$this->setFinalWeight($value);
				break;
			case 6:
				$this->setIsProm($value);
				break;
			case 7:
				$this->setPromPrice($value);
				break;
			case 8:
				$this->setIsDynamicPrice($value);
				break;
			case 9:
				$this->setDynamicPrice($value);
				break;
			case 10:
				$this->setDynamicPriceWhatIf($value);
				break;
			case 11:
				$this->setShow($value);
				break;
			case 12:
				$this->setIsAvailable($value);
				break;
			case 13:
				$this->setNotice($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ShippingTypesPricesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTypeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPackagingTypeId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPrice($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setInitialWeight($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFinalWeight($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setIsProm($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPromPrice($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setIsDynamicPrice($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDynamicPrice($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDynamicPriceWhatIf($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setShow($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setIsAvailable($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setNotice($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ShippingTypesPricesPeer::DATABASE_NAME);

		if ($this->isColumnModified(ShippingTypesPricesPeer::ID)) $criteria->add(ShippingTypesPricesPeer::ID, $this->id);
		if ($this->isColumnModified(ShippingTypesPricesPeer::TYPE_ID)) $criteria->add(ShippingTypesPricesPeer::TYPE_ID, $this->type_id);
		if ($this->isColumnModified(ShippingTypesPricesPeer::PACKAGING_TYPE_ID)) $criteria->add(ShippingTypesPricesPeer::PACKAGING_TYPE_ID, $this->packaging_type_id);
		if ($this->isColumnModified(ShippingTypesPricesPeer::PRICE)) $criteria->add(ShippingTypesPricesPeer::PRICE, $this->price);
		if ($this->isColumnModified(ShippingTypesPricesPeer::INITIAL_WEIGHT)) $criteria->add(ShippingTypesPricesPeer::INITIAL_WEIGHT, $this->initial_weight);
		if ($this->isColumnModified(ShippingTypesPricesPeer::FINAL_WEIGHT)) $criteria->add(ShippingTypesPricesPeer::FINAL_WEIGHT, $this->final_weight);
		if ($this->isColumnModified(ShippingTypesPricesPeer::IS_PROM)) $criteria->add(ShippingTypesPricesPeer::IS_PROM, $this->is_prom);
		if ($this->isColumnModified(ShippingTypesPricesPeer::PROM_PRICE)) $criteria->add(ShippingTypesPricesPeer::PROM_PRICE, $this->prom_price);
		if ($this->isColumnModified(ShippingTypesPricesPeer::IS_DYNAMIC_PRICE)) $criteria->add(ShippingTypesPricesPeer::IS_DYNAMIC_PRICE, $this->is_dynamic_price);
		if ($this->isColumnModified(ShippingTypesPricesPeer::DYNAMIC_PRICE)) $criteria->add(ShippingTypesPricesPeer::DYNAMIC_PRICE, $this->dynamic_price);
		if ($this->isColumnModified(ShippingTypesPricesPeer::DYNAMIC_PRICE_WHAT_IF)) $criteria->add(ShippingTypesPricesPeer::DYNAMIC_PRICE_WHAT_IF, $this->dynamic_price_what_if);
		if ($this->isColumnModified(ShippingTypesPricesPeer::SHOW)) $criteria->add(ShippingTypesPricesPeer::SHOW, $this->show);
		if ($this->isColumnModified(ShippingTypesPricesPeer::IS_AVAILABLE)) $criteria->add(ShippingTypesPricesPeer::IS_AVAILABLE, $this->is_available);
		if ($this->isColumnModified(ShippingTypesPricesPeer::NOTICE)) $criteria->add(ShippingTypesPricesPeer::NOTICE, $this->notice);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ShippingTypesPricesPeer::DATABASE_NAME);

		$criteria->add(ShippingTypesPricesPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ShippingTypesPrices (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTypeId($this->type_id);

		$copyObj->setPackagingTypeId($this->packaging_type_id);

		$copyObj->setPrice($this->price);

		$copyObj->setInitialWeight($this->initial_weight);

		$copyObj->setFinalWeight($this->final_weight);

		$copyObj->setIsProm($this->is_prom);

		$copyObj->setPromPrice($this->prom_price);

		$copyObj->setIsDynamicPrice($this->is_dynamic_price);

		$copyObj->setDynamicPrice($this->dynamic_price);

		$copyObj->setDynamicPriceWhatIf($this->dynamic_price_what_if);

		$copyObj->setShow($this->show);

		$copyObj->setIsAvailable($this->is_available);

		$copyObj->setNotice($this->notice);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ShippingTypesPrices Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ShippingTypesPricesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ShippingTypesPricesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a ShippingTypes object.
	 *
	 * @param      ShippingTypes $v
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setShippingTypes(ShippingTypes $v = null)
	{
		if ($v === null) {
			$this->setTypeId(NULL);
		} else {
			$this->setTypeId($v->getId());
		}

		$this->aShippingTypes = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ShippingTypes object, it will not be re-added.
		if ($v !== null) {
			$v->addShippingTypesPrices($this);
		}

		return $this;
	}


	/**
	 * Get the associated ShippingTypes object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ShippingTypes The associated ShippingTypes object.
	 * @throws     PropelException
	 */
	public function getShippingTypes(PropelPDO $con = null)
	{
		if ($this->aShippingTypes === null && ($this->type_id !== null)) {
			$this->aShippingTypes = ShippingTypesPeer::retrieveByPk($this->type_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aShippingTypes->addShippingTypesPricess($this);
			 */
		}
		return $this->aShippingTypes;
	}

	/**
	 * Declares an association between this object and a PackagingTypes object.
	 *
	 * @param      PackagingTypes $v
	 * @return     ShippingTypesPrices The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPackagingTypes(PackagingTypes $v = null)
	{
		if ($v === null) {
			$this->setPackagingTypeId(NULL);
		} else {
			$this->setPackagingTypeId($v->getId());
		}

		$this->aPackagingTypes = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PackagingTypes object, it will not be re-added.
		if ($v !== null) {
			$v->addShippingTypesPrices($this);
		}

		return $this;
	}


	/**
	 * Get the associated PackagingTypes object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PackagingTypes The associated PackagingTypes object.
	 * @throws     PropelException
	 */
	public function getPackagingTypes(PropelPDO $con = null)
	{
		if ($this->aPackagingTypes === null && ($this->packaging_type_id !== null)) {
			$this->aPackagingTypes = PackagingTypesPeer::retrieveByPk($this->packaging_type_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPackagingTypes->addShippingTypesPricess($this);
			 */
		}
		return $this->aPackagingTypes;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aShippingTypes = null;
			$this->aPackagingTypes = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseShippingTypesPrices:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseShippingTypesPrices::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseShippingTypesPrices
