<?php

/**
 * Base class that represents a row from the 'courier' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/15/11 12:03:03
 *
 * @package    lib.model.om
 */
abstract class BaseCourier extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CourierPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the available field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $available;

	/**
	 * The value for the client_nr field.
	 * @var        string
	 */
	protected $client_nr;

	/**
	 * The value for the api_key field.
	 * @var        string
	 */
	protected $api_key;

	/**
	 * The value for the login field.
	 * @var        string
	 */
	protected $login;

	/**
	 * The value for the pass field.
	 * @var        string
	 */
	protected $pass;

	/**
	 * The value for the petrol_charge field.
	 * Note: this column has a database default value of: '0.00'
	 * @var        string
	 */
	protected $petrol_charge;

	/**
	 * The value for the start_work_time field.
	 * @var        string
	 */
	protected $start_work_time;

	/**
	 * The value for the end_work_time field.
	 * @var        string
	 */
	protected $end_work_time;

	/**
	 * The value for the desc field.
	 * @var        string
	 */
	protected $desc;

	/**
	 * @var        array PackagingTypes[] Collection to store aggregation of PackagingTypes objects.
	 */
	protected $collPackagingTypess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPackagingTypess.
	 */
	private $lastPackagingTypesCriteria = null;

	/**
	 * @var        array OrderShipping[] Collection to store aggregation of OrderShipping objects.
	 */
	protected $collOrderShippings;

	/**
	 * @var        Criteria The criteria used to select the current contents of collOrderShippings.
	 */
	private $lastOrderShippingCriteria = null;

	/**
	 * @var        array ShippingTypesGroups[] Collection to store aggregation of ShippingTypesGroups objects.
	 */
	protected $collShippingTypesGroupss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collShippingTypesGroupss.
	 */
	private $lastShippingTypesGroupsCriteria = null;

	/**
	 * @var        array ShippingOptions[] Collection to store aggregation of ShippingOptions objects.
	 */
	protected $collShippingOptionss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collShippingOptionss.
	 */
	private $lastShippingOptionsCriteria = null;

	/**
	 * @var        array InsuranceRates[] Collection to store aggregation of InsuranceRates objects.
	 */
	protected $collInsuranceRatess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collInsuranceRatess.
	 */
	private $lastInsuranceRatesCriteria = null;

	/**
	 * @var        array Zones[] Collection to store aggregation of Zones objects.
	 */
	protected $collZoness;

	/**
	 * @var        Criteria The criteria used to select the current contents of collZoness.
	 */
	private $lastZonesCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'CourierPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->available = true;
		$this->petrol_charge = '0.00';
	}

	/**
	 * Initializes internal state of BaseCourier object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [available] column value.
	 * 
	 * @return     boolean
	 */
	public function getAvailable()
	{
		return $this->available;
	}

	/**
	 * Get the [client_nr] column value.
	 * 
	 * @return     string
	 */
	public function getClientNr()
	{
		return $this->client_nr;
	}

	/**
	 * Get the [api_key] column value.
	 * 
	 * @return     string
	 */
	public function getApiKey()
	{
		return $this->api_key;
	}

	/**
	 * Get the [login] column value.
	 * 
	 * @return     string
	 */
	public function getLogin()
	{
		return $this->login;
	}

	/**
	 * Get the [pass] column value.
	 * 
	 * @return     string
	 */
	public function getPass()
	{
		return $this->pass;
	}

	/**
	 * Get the [petrol_charge] column value.
	 * 
	 * @return     string
	 */
	public function getPetrolCharge()
	{
		return $this->petrol_charge;
	}

	/**
	 * Get the [optionally formatted] temporal [start_work_time] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStartWorkTime($format = 'H:i:s')
	{
		if ($this->start_work_time === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->start_work_time);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->start_work_time, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [end_work_time] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getEndWorkTime($format = 'H:i:s')
	{
		if ($this->end_work_time === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->end_work_time);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->end_work_time, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [desc] column value.
	 * 
	 * @return     string
	 */
	public function getDesc()
	{
		return $this->desc;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CourierPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = CourierPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [available] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setAvailable($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->available !== $v || $this->isNew()) {
			$this->available = $v;
			$this->modifiedColumns[] = CourierPeer::AVAILABLE;
		}

		return $this;
	} // setAvailable()

	/**
	 * Set the value of [client_nr] column.
	 * 
	 * @param      string $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setClientNr($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->client_nr !== $v) {
			$this->client_nr = $v;
			$this->modifiedColumns[] = CourierPeer::CLIENT_NR;
		}

		return $this;
	} // setClientNr()

	/**
	 * Set the value of [api_key] column.
	 * 
	 * @param      string $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setApiKey($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->api_key !== $v) {
			$this->api_key = $v;
			$this->modifiedColumns[] = CourierPeer::API_KEY;
		}

		return $this;
	} // setApiKey()

	/**
	 * Set the value of [login] column.
	 * 
	 * @param      string $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setLogin($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->login !== $v) {
			$this->login = $v;
			$this->modifiedColumns[] = CourierPeer::LOGIN;
		}

		return $this;
	} // setLogin()

	/**
	 * Set the value of [pass] column.
	 * 
	 * @param      string $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setPass($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pass !== $v) {
			$this->pass = $v;
			$this->modifiedColumns[] = CourierPeer::PASS;
		}

		return $this;
	} // setPass()

	/**
	 * Set the value of [petrol_charge] column.
	 * 
	 * @param      string $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setPetrolCharge($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->petrol_charge !== $v || $this->isNew()) {
			$this->petrol_charge = $v;
			$this->modifiedColumns[] = CourierPeer::PETROL_CHARGE;
		}

		return $this;
	} // setPetrolCharge()

	/**
	 * Sets the value of [start_work_time] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setStartWorkTime($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->start_work_time !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->start_work_time !== null && $tmpDt = new DateTime($this->start_work_time)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->start_work_time = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = CourierPeer::START_WORK_TIME;
			}
		} // if either are not null

		return $this;
	} // setStartWorkTime()

	/**
	 * Sets the value of [end_work_time] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setEndWorkTime($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->end_work_time !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->end_work_time !== null && $tmpDt = new DateTime($this->end_work_time)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->end_work_time = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = CourierPeer::END_WORK_TIME;
			}
		} // if either are not null

		return $this;
	} // setEndWorkTime()

	/**
	 * Set the value of [desc] column.
	 * 
	 * @param      string $v new value
	 * @return     Courier The current object (for fluent API support)
	 */
	public function setDesc($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->desc !== $v) {
			$this->desc = $v;
			$this->modifiedColumns[] = CourierPeer::DESC;
		}

		return $this;
	} // setDesc()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->available !== true) {
				return false;
			}

			if ($this->petrol_charge !== '0.00') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->available = ($row[$startcol + 2] !== null) ? (boolean) $row[$startcol + 2] : null;
			$this->client_nr = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->api_key = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->login = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->pass = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->petrol_charge = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->start_work_time = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->end_work_time = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->desc = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = CourierPeer::NUM_COLUMNS - CourierPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Courier object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CourierPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CourierPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collPackagingTypess = null;
			$this->lastPackagingTypesCriteria = null;

			$this->collOrderShippings = null;
			$this->lastOrderShippingCriteria = null;

			$this->collShippingTypesGroupss = null;
			$this->lastShippingTypesGroupsCriteria = null;

			$this->collShippingOptionss = null;
			$this->lastShippingOptionsCriteria = null;

			$this->collInsuranceRatess = null;
			$this->lastInsuranceRatesCriteria = null;

			$this->collZoness = null;
			$this->lastZonesCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CourierPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCourier:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				CourierPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCourier:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CourierPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCourier:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCourier:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				CourierPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CourierPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CourierPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CourierPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPackagingTypess !== null) {
				foreach ($this->collPackagingTypess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collOrderShippings !== null) {
				foreach ($this->collOrderShippings as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collShippingTypesGroupss !== null) {
				foreach ($this->collShippingTypesGroupss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collShippingOptionss !== null) {
				foreach ($this->collShippingOptionss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collInsuranceRatess !== null) {
				foreach ($this->collInsuranceRatess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collZoness !== null) {
				foreach ($this->collZoness as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = CourierPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPackagingTypess !== null) {
					foreach ($this->collPackagingTypess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collOrderShippings !== null) {
					foreach ($this->collOrderShippings as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collShippingTypesGroupss !== null) {
					foreach ($this->collShippingTypesGroupss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collShippingOptionss !== null) {
					foreach ($this->collShippingOptionss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collInsuranceRatess !== null) {
					foreach ($this->collInsuranceRatess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collZoness !== null) {
					foreach ($this->collZoness as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CourierPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getAvailable();
				break;
			case 3:
				return $this->getClientNr();
				break;
			case 4:
				return $this->getApiKey();
				break;
			case 5:
				return $this->getLogin();
				break;
			case 6:
				return $this->getPass();
				break;
			case 7:
				return $this->getPetrolCharge();
				break;
			case 8:
				return $this->getStartWorkTime();
				break;
			case 9:
				return $this->getEndWorkTime();
				break;
			case 10:
				return $this->getDesc();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CourierPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getAvailable(),
			$keys[3] => $this->getClientNr(),
			$keys[4] => $this->getApiKey(),
			$keys[5] => $this->getLogin(),
			$keys[6] => $this->getPass(),
			$keys[7] => $this->getPetrolCharge(),
			$keys[8] => $this->getStartWorkTime(),
			$keys[9] => $this->getEndWorkTime(),
			$keys[10] => $this->getDesc(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CourierPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setAvailable($value);
				break;
			case 3:
				$this->setClientNr($value);
				break;
			case 4:
				$this->setApiKey($value);
				break;
			case 5:
				$this->setLogin($value);
				break;
			case 6:
				$this->setPass($value);
				break;
			case 7:
				$this->setPetrolCharge($value);
				break;
			case 8:
				$this->setStartWorkTime($value);
				break;
			case 9:
				$this->setEndWorkTime($value);
				break;
			case 10:
				$this->setDesc($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CourierPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAvailable($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setClientNr($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setApiKey($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setLogin($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPass($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPetrolCharge($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setStartWorkTime($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setEndWorkTime($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDesc($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CourierPeer::DATABASE_NAME);

		if ($this->isColumnModified(CourierPeer::ID)) $criteria->add(CourierPeer::ID, $this->id);
		if ($this->isColumnModified(CourierPeer::NAME)) $criteria->add(CourierPeer::NAME, $this->name);
		if ($this->isColumnModified(CourierPeer::AVAILABLE)) $criteria->add(CourierPeer::AVAILABLE, $this->available);
		if ($this->isColumnModified(CourierPeer::CLIENT_NR)) $criteria->add(CourierPeer::CLIENT_NR, $this->client_nr);
		if ($this->isColumnModified(CourierPeer::API_KEY)) $criteria->add(CourierPeer::API_KEY, $this->api_key);
		if ($this->isColumnModified(CourierPeer::LOGIN)) $criteria->add(CourierPeer::LOGIN, $this->login);
		if ($this->isColumnModified(CourierPeer::PASS)) $criteria->add(CourierPeer::PASS, $this->pass);
		if ($this->isColumnModified(CourierPeer::PETROL_CHARGE)) $criteria->add(CourierPeer::PETROL_CHARGE, $this->petrol_charge);
		if ($this->isColumnModified(CourierPeer::START_WORK_TIME)) $criteria->add(CourierPeer::START_WORK_TIME, $this->start_work_time);
		if ($this->isColumnModified(CourierPeer::END_WORK_TIME)) $criteria->add(CourierPeer::END_WORK_TIME, $this->end_work_time);
		if ($this->isColumnModified(CourierPeer::DESC)) $criteria->add(CourierPeer::DESC, $this->desc);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CourierPeer::DATABASE_NAME);

		$criteria->add(CourierPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Courier (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setAvailable($this->available);

		$copyObj->setClientNr($this->client_nr);

		$copyObj->setApiKey($this->api_key);

		$copyObj->setLogin($this->login);

		$copyObj->setPass($this->pass);

		$copyObj->setPetrolCharge($this->petrol_charge);

		$copyObj->setStartWorkTime($this->start_work_time);

		$copyObj->setEndWorkTime($this->end_work_time);

		$copyObj->setDesc($this->desc);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPackagingTypess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPackagingTypes($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getOrderShippings() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addOrderShipping($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getShippingTypesGroupss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addShippingTypesGroups($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getShippingOptionss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addShippingOptions($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getInsuranceRatess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addInsuranceRates($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getZoness() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addZones($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Courier Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CourierPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CourierPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collPackagingTypess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPackagingTypess()
	 */
	public function clearPackagingTypess()
	{
		$this->collPackagingTypess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPackagingTypess collection (array).
	 *
	 * By default this just sets the collPackagingTypess collection to an empty array (like clearcollPackagingTypess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPackagingTypess()
	{
		$this->collPackagingTypess = array();
	}

	/**
	 * Gets an array of PackagingTypes objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Courier has previously been saved, it will retrieve
	 * related PackagingTypess from storage. If this Courier is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PackagingTypes[]
	 * @throws     PropelException
	 */
	public function getPackagingTypess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPackagingTypess === null) {
			if ($this->isNew()) {
			   $this->collPackagingTypess = array();
			} else {

				$criteria->add(PackagingTypesPeer::COURIER_ID, $this->id);

				PackagingTypesPeer::addSelectColumns($criteria);
				$this->collPackagingTypess = PackagingTypesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PackagingTypesPeer::COURIER_ID, $this->id);

				PackagingTypesPeer::addSelectColumns($criteria);
				if (!isset($this->lastPackagingTypesCriteria) || !$this->lastPackagingTypesCriteria->equals($criteria)) {
					$this->collPackagingTypess = PackagingTypesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPackagingTypesCriteria = $criteria;
		return $this->collPackagingTypess;
	}

	/**
	 * Returns the number of related PackagingTypes objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PackagingTypes objects.
	 * @throws     PropelException
	 */
	public function countPackagingTypess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPackagingTypess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PackagingTypesPeer::COURIER_ID, $this->id);

				$count = PackagingTypesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PackagingTypesPeer::COURIER_ID, $this->id);

				if (!isset($this->lastPackagingTypesCriteria) || !$this->lastPackagingTypesCriteria->equals($criteria)) {
					$count = PackagingTypesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPackagingTypess);
				}
			} else {
				$count = count($this->collPackagingTypess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PackagingTypes object to this object
	 * through the PackagingTypes foreign key attribute.
	 *
	 * @param      PackagingTypes $l PackagingTypes
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPackagingTypes(PackagingTypes $l)
	{
		if ($this->collPackagingTypess === null) {
			$this->initPackagingTypess();
		}
		if (!in_array($l, $this->collPackagingTypess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPackagingTypess, $l);
			$l->setCourier($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Courier is new, it will return
	 * an empty collection; or if this Courier has previously
	 * been saved, it will retrieve related PackagingTypess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Courier.
	 */
	public function getPackagingTypessJoinPackagingGroups($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPackagingTypess === null) {
			if ($this->isNew()) {
				$this->collPackagingTypess = array();
			} else {

				$criteria->add(PackagingTypesPeer::COURIER_ID, $this->id);

				$this->collPackagingTypess = PackagingTypesPeer::doSelectJoinPackagingGroups($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PackagingTypesPeer::COURIER_ID, $this->id);

			if (!isset($this->lastPackagingTypesCriteria) || !$this->lastPackagingTypesCriteria->equals($criteria)) {
				$this->collPackagingTypess = PackagingTypesPeer::doSelectJoinPackagingGroups($criteria, $con, $join_behavior);
			}
		}
		$this->lastPackagingTypesCriteria = $criteria;

		return $this->collPackagingTypess;
	}

	/**
	 * Clears out the collOrderShippings collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addOrderShippings()
	 */
	public function clearOrderShippings()
	{
		$this->collOrderShippings = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collOrderShippings collection (array).
	 *
	 * By default this just sets the collOrderShippings collection to an empty array (like clearcollOrderShippings());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initOrderShippings()
	{
		$this->collOrderShippings = array();
	}

	/**
	 * Gets an array of OrderShipping objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Courier has previously been saved, it will retrieve
	 * related OrderShippings from storage. If this Courier is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array OrderShipping[]
	 * @throws     PropelException
	 */
	public function getOrderShippings($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrderShippings === null) {
			if ($this->isNew()) {
			   $this->collOrderShippings = array();
			} else {

				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				OrderShippingPeer::addSelectColumns($criteria);
				$this->collOrderShippings = OrderShippingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				OrderShippingPeer::addSelectColumns($criteria);
				if (!isset($this->lastOrderShippingCriteria) || !$this->lastOrderShippingCriteria->equals($criteria)) {
					$this->collOrderShippings = OrderShippingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastOrderShippingCriteria = $criteria;
		return $this->collOrderShippings;
	}

	/**
	 * Returns the number of related OrderShipping objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related OrderShipping objects.
	 * @throws     PropelException
	 */
	public function countOrderShippings(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collOrderShippings === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				$count = OrderShippingPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				if (!isset($this->lastOrderShippingCriteria) || !$this->lastOrderShippingCriteria->equals($criteria)) {
					$count = OrderShippingPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collOrderShippings);
				}
			} else {
				$count = count($this->collOrderShippings);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a OrderShipping object to this object
	 * through the OrderShipping foreign key attribute.
	 *
	 * @param      OrderShipping $l OrderShipping
	 * @return     void
	 * @throws     PropelException
	 */
	public function addOrderShipping(OrderShipping $l)
	{
		if ($this->collOrderShippings === null) {
			$this->initOrderShippings();
		}
		if (!in_array($l, $this->collOrderShippings, true)) { // only add it if the **same** object is not already associated
			array_push($this->collOrderShippings, $l);
			$l->setCourier($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Courier is new, it will return
	 * an empty collection; or if this Courier has previously
	 * been saved, it will retrieve related OrderShippings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Courier.
	 */
	public function getOrderShippingsJoinUsers($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrderShippings === null) {
			if ($this->isNew()) {
				$this->collOrderShippings = array();
			} else {

				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				$this->collOrderShippings = OrderShippingPeer::doSelectJoinUsers($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

			if (!isset($this->lastOrderShippingCriteria) || !$this->lastOrderShippingCriteria->equals($criteria)) {
				$this->collOrderShippings = OrderShippingPeer::doSelectJoinUsers($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrderShippingCriteria = $criteria;

		return $this->collOrderShippings;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Courier is new, it will return
	 * an empty collection; or if this Courier has previously
	 * been saved, it will retrieve related OrderShippings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Courier.
	 */
	public function getOrderShippingsJoinShippingTypes($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrderShippings === null) {
			if ($this->isNew()) {
				$this->collOrderShippings = array();
			} else {

				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				$this->collOrderShippings = OrderShippingPeer::doSelectJoinShippingTypes($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

			if (!isset($this->lastOrderShippingCriteria) || !$this->lastOrderShippingCriteria->equals($criteria)) {
				$this->collOrderShippings = OrderShippingPeer::doSelectJoinShippingTypes($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrderShippingCriteria = $criteria;

		return $this->collOrderShippings;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Courier is new, it will return
	 * an empty collection; or if this Courier has previously
	 * been saved, it will retrieve related OrderShippings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Courier.
	 */
	public function getOrderShippingsJoinZones($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrderShippings === null) {
			if ($this->isNew()) {
				$this->collOrderShippings = array();
			} else {

				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				$this->collOrderShippings = OrderShippingPeer::doSelectJoinZones($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

			if (!isset($this->lastOrderShippingCriteria) || !$this->lastOrderShippingCriteria->equals($criteria)) {
				$this->collOrderShippings = OrderShippingPeer::doSelectJoinZones($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrderShippingCriteria = $criteria;

		return $this->collOrderShippings;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Courier is new, it will return
	 * an empty collection; or if this Courier has previously
	 * been saved, it will retrieve related OrderShippings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Courier.
	 */
	public function getOrderShippingsJoinCountries($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrderShippings === null) {
			if ($this->isNew()) {
				$this->collOrderShippings = array();
			} else {

				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				$this->collOrderShippings = OrderShippingPeer::doSelectJoinCountries($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

			if (!isset($this->lastOrderShippingCriteria) || !$this->lastOrderShippingCriteria->equals($criteria)) {
				$this->collOrderShippings = OrderShippingPeer::doSelectJoinCountries($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrderShippingCriteria = $criteria;

		return $this->collOrderShippings;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Courier is new, it will return
	 * an empty collection; or if this Courier has previously
	 * been saved, it will retrieve related OrderShippings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Courier.
	 */
	public function getOrderShippingsJoinPackagingTypes($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrderShippings === null) {
			if ($this->isNew()) {
				$this->collOrderShippings = array();
			} else {

				$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

				$this->collOrderShippings = OrderShippingPeer::doSelectJoinPackagingTypes($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrderShippingPeer::COURIER_ID, $this->id);

			if (!isset($this->lastOrderShippingCriteria) || !$this->lastOrderShippingCriteria->equals($criteria)) {
				$this->collOrderShippings = OrderShippingPeer::doSelectJoinPackagingTypes($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrderShippingCriteria = $criteria;

		return $this->collOrderShippings;
	}

	/**
	 * Clears out the collShippingTypesGroupss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addShippingTypesGroupss()
	 */
	public function clearShippingTypesGroupss()
	{
		$this->collShippingTypesGroupss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collShippingTypesGroupss collection (array).
	 *
	 * By default this just sets the collShippingTypesGroupss collection to an empty array (like clearcollShippingTypesGroupss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initShippingTypesGroupss()
	{
		$this->collShippingTypesGroupss = array();
	}

	/**
	 * Gets an array of ShippingTypesGroups objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Courier has previously been saved, it will retrieve
	 * related ShippingTypesGroupss from storage. If this Courier is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ShippingTypesGroups[]
	 * @throws     PropelException
	 */
	public function getShippingTypesGroupss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collShippingTypesGroupss === null) {
			if ($this->isNew()) {
			   $this->collShippingTypesGroupss = array();
			} else {

				$criteria->add(ShippingTypesGroupsPeer::COURIER_ID, $this->id);

				ShippingTypesGroupsPeer::addSelectColumns($criteria);
				$this->collShippingTypesGroupss = ShippingTypesGroupsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ShippingTypesGroupsPeer::COURIER_ID, $this->id);

				ShippingTypesGroupsPeer::addSelectColumns($criteria);
				if (!isset($this->lastShippingTypesGroupsCriteria) || !$this->lastShippingTypesGroupsCriteria->equals($criteria)) {
					$this->collShippingTypesGroupss = ShippingTypesGroupsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastShippingTypesGroupsCriteria = $criteria;
		return $this->collShippingTypesGroupss;
	}

	/**
	 * Returns the number of related ShippingTypesGroups objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ShippingTypesGroups objects.
	 * @throws     PropelException
	 */
	public function countShippingTypesGroupss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collShippingTypesGroupss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ShippingTypesGroupsPeer::COURIER_ID, $this->id);

				$count = ShippingTypesGroupsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ShippingTypesGroupsPeer::COURIER_ID, $this->id);

				if (!isset($this->lastShippingTypesGroupsCriteria) || !$this->lastShippingTypesGroupsCriteria->equals($criteria)) {
					$count = ShippingTypesGroupsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collShippingTypesGroupss);
				}
			} else {
				$count = count($this->collShippingTypesGroupss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ShippingTypesGroups object to this object
	 * through the ShippingTypesGroups foreign key attribute.
	 *
	 * @param      ShippingTypesGroups $l ShippingTypesGroups
	 * @return     void
	 * @throws     PropelException
	 */
	public function addShippingTypesGroups(ShippingTypesGroups $l)
	{
		if ($this->collShippingTypesGroupss === null) {
			$this->initShippingTypesGroupss();
		}
		if (!in_array($l, $this->collShippingTypesGroupss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collShippingTypesGroupss, $l);
			$l->setCourier($this);
		}
	}

	/**
	 * Clears out the collShippingOptionss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addShippingOptionss()
	 */
	public function clearShippingOptionss()
	{
		$this->collShippingOptionss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collShippingOptionss collection (array).
	 *
	 * By default this just sets the collShippingOptionss collection to an empty array (like clearcollShippingOptionss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initShippingOptionss()
	{
		$this->collShippingOptionss = array();
	}

	/**
	 * Gets an array of ShippingOptions objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Courier has previously been saved, it will retrieve
	 * related ShippingOptionss from storage. If this Courier is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ShippingOptions[]
	 * @throws     PropelException
	 */
	public function getShippingOptionss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collShippingOptionss === null) {
			if ($this->isNew()) {
			   $this->collShippingOptionss = array();
			} else {

				$criteria->add(ShippingOptionsPeer::COURIER_ID, $this->id);

				ShippingOptionsPeer::addSelectColumns($criteria);
				$this->collShippingOptionss = ShippingOptionsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ShippingOptionsPeer::COURIER_ID, $this->id);

				ShippingOptionsPeer::addSelectColumns($criteria);
				if (!isset($this->lastShippingOptionsCriteria) || !$this->lastShippingOptionsCriteria->equals($criteria)) {
					$this->collShippingOptionss = ShippingOptionsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastShippingOptionsCriteria = $criteria;
		return $this->collShippingOptionss;
	}

	/**
	 * Returns the number of related ShippingOptions objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ShippingOptions objects.
	 * @throws     PropelException
	 */
	public function countShippingOptionss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collShippingOptionss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ShippingOptionsPeer::COURIER_ID, $this->id);

				$count = ShippingOptionsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ShippingOptionsPeer::COURIER_ID, $this->id);

				if (!isset($this->lastShippingOptionsCriteria) || !$this->lastShippingOptionsCriteria->equals($criteria)) {
					$count = ShippingOptionsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collShippingOptionss);
				}
			} else {
				$count = count($this->collShippingOptionss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ShippingOptions object to this object
	 * through the ShippingOptions foreign key attribute.
	 *
	 * @param      ShippingOptions $l ShippingOptions
	 * @return     void
	 * @throws     PropelException
	 */
	public function addShippingOptions(ShippingOptions $l)
	{
		if ($this->collShippingOptionss === null) {
			$this->initShippingOptionss();
		}
		if (!in_array($l, $this->collShippingOptionss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collShippingOptionss, $l);
			$l->setCourier($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Courier is new, it will return
	 * an empty collection; or if this Courier has previously
	 * been saved, it will retrieve related ShippingOptionss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Courier.
	 */
	public function getShippingOptionssJoinCountries($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collShippingOptionss === null) {
			if ($this->isNew()) {
				$this->collShippingOptionss = array();
			} else {

				$criteria->add(ShippingOptionsPeer::COURIER_ID, $this->id);

				$this->collShippingOptionss = ShippingOptionsPeer::doSelectJoinCountries($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ShippingOptionsPeer::COURIER_ID, $this->id);

			if (!isset($this->lastShippingOptionsCriteria) || !$this->lastShippingOptionsCriteria->equals($criteria)) {
				$this->collShippingOptionss = ShippingOptionsPeer::doSelectJoinCountries($criteria, $con, $join_behavior);
			}
		}
		$this->lastShippingOptionsCriteria = $criteria;

		return $this->collShippingOptionss;
	}

	/**
	 * Clears out the collInsuranceRatess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addInsuranceRatess()
	 */
	public function clearInsuranceRatess()
	{
		$this->collInsuranceRatess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collInsuranceRatess collection (array).
	 *
	 * By default this just sets the collInsuranceRatess collection to an empty array (like clearcollInsuranceRatess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initInsuranceRatess()
	{
		$this->collInsuranceRatess = array();
	}

	/**
	 * Gets an array of InsuranceRates objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Courier has previously been saved, it will retrieve
	 * related InsuranceRatess from storage. If this Courier is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array InsuranceRates[]
	 * @throws     PropelException
	 */
	public function getInsuranceRatess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collInsuranceRatess === null) {
			if ($this->isNew()) {
			   $this->collInsuranceRatess = array();
			} else {

				$criteria->add(InsuranceRatesPeer::COURIER_ID, $this->id);

				InsuranceRatesPeer::addSelectColumns($criteria);
				$this->collInsuranceRatess = InsuranceRatesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(InsuranceRatesPeer::COURIER_ID, $this->id);

				InsuranceRatesPeer::addSelectColumns($criteria);
				if (!isset($this->lastInsuranceRatesCriteria) || !$this->lastInsuranceRatesCriteria->equals($criteria)) {
					$this->collInsuranceRatess = InsuranceRatesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastInsuranceRatesCriteria = $criteria;
		return $this->collInsuranceRatess;
	}

	/**
	 * Returns the number of related InsuranceRates objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related InsuranceRates objects.
	 * @throws     PropelException
	 */
	public function countInsuranceRatess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collInsuranceRatess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(InsuranceRatesPeer::COURIER_ID, $this->id);

				$count = InsuranceRatesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(InsuranceRatesPeer::COURIER_ID, $this->id);

				if (!isset($this->lastInsuranceRatesCriteria) || !$this->lastInsuranceRatesCriteria->equals($criteria)) {
					$count = InsuranceRatesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collInsuranceRatess);
				}
			} else {
				$count = count($this->collInsuranceRatess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a InsuranceRates object to this object
	 * through the InsuranceRates foreign key attribute.
	 *
	 * @param      InsuranceRates $l InsuranceRates
	 * @return     void
	 * @throws     PropelException
	 */
	public function addInsuranceRates(InsuranceRates $l)
	{
		if ($this->collInsuranceRatess === null) {
			$this->initInsuranceRatess();
		}
		if (!in_array($l, $this->collInsuranceRatess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collInsuranceRatess, $l);
			$l->setCourier($this);
		}
	}

	/**
	 * Clears out the collZoness collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addZoness()
	 */
	public function clearZoness()
	{
		$this->collZoness = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collZoness collection (array).
	 *
	 * By default this just sets the collZoness collection to an empty array (like clearcollZoness());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initZoness()
	{
		$this->collZoness = array();
	}

	/**
	 * Gets an array of Zones objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Courier has previously been saved, it will retrieve
	 * related Zoness from storage. If this Courier is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Zones[]
	 * @throws     PropelException
	 */
	public function getZoness($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collZoness === null) {
			if ($this->isNew()) {
			   $this->collZoness = array();
			} else {

				$criteria->add(ZonesPeer::COURIER_ID, $this->id);

				ZonesPeer::addSelectColumns($criteria);
				$this->collZoness = ZonesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ZonesPeer::COURIER_ID, $this->id);

				ZonesPeer::addSelectColumns($criteria);
				if (!isset($this->lastZonesCriteria) || !$this->lastZonesCriteria->equals($criteria)) {
					$this->collZoness = ZonesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastZonesCriteria = $criteria;
		return $this->collZoness;
	}

	/**
	 * Returns the number of related Zones objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Zones objects.
	 * @throws     PropelException
	 */
	public function countZoness(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CourierPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collZoness === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ZonesPeer::COURIER_ID, $this->id);

				$count = ZonesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ZonesPeer::COURIER_ID, $this->id);

				if (!isset($this->lastZonesCriteria) || !$this->lastZonesCriteria->equals($criteria)) {
					$count = ZonesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collZoness);
				}
			} else {
				$count = count($this->collZoness);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Zones object to this object
	 * through the Zones foreign key attribute.
	 *
	 * @param      Zones $l Zones
	 * @return     void
	 * @throws     PropelException
	 */
	public function addZones(Zones $l)
	{
		if ($this->collZoness === null) {
			$this->initZoness();
		}
		if (!in_array($l, $this->collZoness, true)) { // only add it if the **same** object is not already associated
			array_push($this->collZoness, $l);
			$l->setCourier($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPackagingTypess) {
				foreach ((array) $this->collPackagingTypess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collOrderShippings) {
				foreach ((array) $this->collOrderShippings as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collShippingTypesGroupss) {
				foreach ((array) $this->collShippingTypesGroupss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collShippingOptionss) {
				foreach ((array) $this->collShippingOptionss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collInsuranceRatess) {
				foreach ((array) $this->collInsuranceRatess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collZoness) {
				foreach ((array) $this->collZoness as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPackagingTypess = null;
		$this->collOrderShippings = null;
		$this->collShippingTypesGroupss = null;
		$this->collShippingOptionss = null;
		$this->collInsuranceRatess = null;
		$this->collZoness = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseCourier:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseCourier::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseCourier
