<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/02 08:04:07

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=fzl_8;host=sql.fzl.nazwa.pl',
  'username' => 'fzl_8',
  'password' => 'chomik84KONIKAN',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
