<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/12 22:12:13
sfConfig::add(array(
  'mod_insurance_rates_enabled' => true,
  'mod_insurance_rates_view_class' => 'sfPHP',
));
