<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/02 08:12:33
sfConfig::add(array(
  'mod_special_offers_enabled' => true,
  'mod_special_offers_view_class' => 'sfPHP',
));
