<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/02 08:12:12
sfConfig::add(array(
  'mod_shipping_types_enabled' => true,
  'mod_shipping_types_view_class' => 'sfPHP',
));
