# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, smoothness/jquery-ui-1.8.9.custom.css]

  javascripts:    [jquery-1.4.4.min.js, jquery-ui/js/jquery-ui-1.8.9.custom.min.js, jquery.accordion.js , swfobject.js, ../sfProtoculousPlugin/js/prototype.js, ../sfProtoculousPlugin/js/builder.js, ../sfProtoculousPlugin/js/scriptaculous.js,  ../sfProtoculousPlugin/js/effects.js]

  has_layout:     true
  layout:         layout
