<?php


/**
 * Skeleton subclass for performing query and update operations on the 'config' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 13 23:14:35 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ConfigPeer extends BaseConfigPeer {
    public static function getConfig($config_name)
    {
        $configs = array();

        $c = new Criteria();
        $c->add(ConfigPeer::NAME, $config_name."%", Criteria::LIKE);

        $results = ConfigPeer::doSelect($c);
        if($results)
        {
                foreach ($results as $res)
                {
                        $configs[$res->getName()] = $res->getValue();
                }
                return $configs;
        }
        else
        {
                return false;
        }
    }

} // ConfigPeer
