<?php


/**
 * Skeleton subclass for performing query and update operations on the 'courier' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Aug 30 14:40:56 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CourierPeer extends BaseCourierPeer {

    public static function getActiveCouriers()
    {
        $c = new Criteria();

        $c->add(CourierPeer::AVAILABLE,1);

        return CourierPeer::doSelect($c);
    }

    public static function getInternationalCouriers()
    {
        $c = new Criteria();

        $c->add(CourierPeer::ID, "courier.id in (select courier_id from zones)", Criteria::CUSTOM);
        return CourierPeer::doSelect($c);
    }

} // CourierPeer
