<?php


/**
 * Skeleton subclass for representing a row from the 'dhl_numbers' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/22/10 02:49:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DhlNumbers extends BaseDhlNumbers {

	/**
	 * Initializes internal state of DhlNumbers object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // DhlNumbers
