<?php


/**
 * Skeleton subclass for representing a row from the 'order_shipping_zones_services' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/13/11 20:49:18
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class OrderShippingZonesServices extends BaseOrderShippingZonesServices {

} // OrderShippingZonesServices
