<?php


/**
 * Skeleton subclass for performing query and update operations on the 'packaging_groups' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov  6 11:39:46 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PackagingGroupsPeer extends BasePackagingGroupsPeer {

    public static function getAvailableGroups()
    {
       $c = new Criteria();
       $c->add(PackagingGroupsPeer::AVAILABLE,1);

       return PackagingGroupsPeer::doSelect($c);
    }

} // PackagingGroupsPeer
