<?php


/**
 * Skeleton subclass for representing a row from the 'questions' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/09/11 23:53:07
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Questions extends BaseQuestions {

} // Questions
