<?php


/**
 * Skeleton subclass for performing query and update operations on the 'shipping_types_groups' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/19/10 19:49:39
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ShippingTypesGroupsPeer extends BaseShippingTypesGroupsPeer {

    public static function getGoupsAndActiveTypes()
    {
        $c = new Criteria();
        $c->add(ShippingTypesGroupsPeer::IS_ACTIVE,1);
        $c->addJoin(ShippingTypesGroupsPeer::ID, ShippingTypesPeer::GROUP_ID);
        $c->add(ShippingTypesPeer::IS_ACTIVE,1);
        $c->add(ShippingTypesPeer::IS_AVAILABLE,1);

        return ShippingTypesGroupsPeer::doSelectJoinAll($c);
    }

     public static function getGoupsAndActiveTypesByPGroup($pack_grup, $weight=null, $courier=null)
    {
        $c = new Criteria();
        $c->add(ShippingTypesGroupsPeer::IS_ACTIVE,1);
        $c->addJoin(ShippingTypesGroupsPeer::ID, ShippingTypesPeer::GROUP_ID);
        $c->addJoin(ShippingTypesPeer::PACKAGING_TYPE_ID, PackagingTypesPeer::ID);
        $c->add(PackagingTypesPeer::GROUP_ID,$pack_grup);
        if(!is_null($weight))
        {
            $c->add(ShippingTypesPeer::FINAL_WEIGHT,$weight, Criteria::GREATER_EQUAL);
            $c->add(ShippingTypesPeer::INITIAL_WEIGHT,$weight, Criteria::LESS_EQUAL);
        }
        if(!is_null($courier))
        {
            $c->add(ShippingTypesGroupsPeer::COURIER_ID,$courier);

        }
        $c->add(ShippingTypesPeer::IS_ACTIVE,1);
        $c->add(ShippingTypesPeer::IS_AVAILABLE,1);

        return ShippingTypesGroupsPeer::doSelectJoinAll($c);
    }


    public static function getByServiceId($service_id, $courier_id)
    {
        $c = new Criteria();
        $c->add(ShippingTypesGroupsPeer::SERVICE_ID,$service_id);
        $c->add(ShippingTypesGroupsPeer::COURIER_ID,$courier_id);

        return $this->doSelectOne($c);
    }

} // ShippingTypesGroupsPeer
