<?php


/**
 * Skeleton subclass for performing query and update operations on the 'shipping_types' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/19/10 19:49:39
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ShippingTypesPeer extends BaseShippingTypesPeer {

    public static function getByServiceId($service_id, $pack_id ,$courier_id)
    {
        $c = new Criteria();

        $c->addJoin(ShippingTypesPeer::GROUP_ID, ShippingTypesGroupsPeer::ID );
        $c->add(ShippingTypesGroupsPeer::SERVICE_ID,$service_id);
        $c->add(ShippingTypesGroupsPeer::COURIER_ID ,$courier_id);
        $c->add(ShippingTypesPeer::PACKAGING_TYPE_ID ,$pack_id);

        return ShippingTypesPeer::doSelectOne($c);
    }

} // ShippingTypesPeer
