<?php


/**
 * Skeleton subclass for representing a row from the 'special_offer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/11/11 19:34:51
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SpecialOffer extends BaseSpecialOffer {

} // SpecialOffer
