<?php


/**
 * Skeleton subclass for performing query and update operations on the 'specjal_offer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/11/11 19:14:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SpecjalOfferPeer extends BaseSpecjalOfferPeer {

} // SpecjalOfferPeer
