<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user_sender' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Oct 26 16:33:50 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserSenderPeer extends BaseUserSenderPeer {

    static public function retrieveForSelect($q, $limit, $user_id=null)
    {
        $criteria = new Criteria();
        if(!is_null($user_id))
            $criteria->add (UserSenderPeer::USER_ID, $user_id);
        $criteria->add(UserSenderPeer::SENDER_NAME, '%'.$q.'%', Criteria::LIKE);
        $criteria->addAscendingOrderByColumn(UserSenderPeer::SENDER_NAME);
        $criteria->setLimit($limit);

        $senders = array();
        foreach (UserSenderPeer::doSelect($criteria) as $sender)
        {
          $senders[] = array(
              'id'              =>  $sender->getId(),
              'address'         =>  $sender->getAddress(),
              'city'            =>  $sender->getCity(),
              'sender_name'     =>  $sender->getSenderName(),
              'street'          =>  $sender->getStreet(),
              'contact_name'    =>  $sender->getContactName(),
              'street_nr'       =>  $sender->getStreetNr(),
              'local_nr'        =>  $sender->getLocalNr(),
              'postcode'        =>  $sender->getPostcode(),
              'tel'             =>  $sender->getTel(),
              'email'           =>  $sender->getEmail()
          );

         
        }

        return $senders;
    }


} // UserSenderPeer
