<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user_recipient' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Oct 26 16:33:50 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserRecipientPeer extends BaseUserRecipientPeer {

    static public function retrieveForSelect($q, $limit, $user_id=null)
    {
        $criteria = new Criteria();
         if(!is_null($user_id))
            $criteria->add (UserRecipientPeer::USER_ID, $user_id);
        $criteria->add(UserRecipientPeer::RECIPIENT_NAME, '%'.$q.'%', Criteria::LIKE);
        $criteria->addAscendingOrderByColumn(UserRecipientPeer::RECIPIENT_NAME);
        $criteria->setLimit($limit);

        $recipients = array();
        foreach (UserRecipientPeer::doSelect($criteria) as $recipient)
        {
          $recipients[] = array(
              'id'              =>  $recipient->getId(),
              'address'         =>  $recipient->getAddress(),
              'city'            =>  $recipient->getCity(),
              'sender_name'     =>  $recipient->getRecipientName(),
              'street'          =>  $recipient->getStreet(),
              'contact_name'    =>  $recipient->getContactName(),
              'street_nr'       =>  $recipient->getStreetNr(),
              'local_nr'        =>  $recipient->getLocalNr(),
              'postcode'        =>  $recipient->getPostcode(),
              'tel'             =>  $recipient->getTel(),
              'email'           =>  $recipient->getEmail()
          );


        }

        return $recipients;
    }

} // UserRecipientPeer
