<?php


/**
 * Skeleton subclass for representing a row from the 'users' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Aug 30 14:40:56 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Users extends BaseUsers {

    public function  __toString() {
        return $this->getEmail();
    }


    public function getDefaultSender()
    {
        $c = new Criteria();
        $c->add(UserSenderPeer::IS_DEFAULT,1);
        $c->add(UserSenderPeer::USER_ID, $this->getId());

        return UserSenderPeer::doSelectOne($c);
    }

} // Users
