<?php


/**
 * Skeleton subclass for representing a row from the 'zones_countries' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/12/11 12:50:49
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ZonesCountries extends BaseZonesCountries {

} // ZonesCountries
