<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/01 18:41:09
sfConfig::add(array(
  'mod_zones_services_enabled' => true,
  'mod_zones_services_view_class' => 'sfPHP',
));
