<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/02 11:28:59
sfConfig::add(array(
  'mod_shipping_types_groups_enabled' => true,
  'mod_shipping_types_groups_view_class' => 'sfPHP',
));
