<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/02 13:52:04
sfConfig::add(array(
  'mod_special_offers_enabled' => true,
  'mod_special_offers_view_class' => 'sfPHP',
));
