<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/02 11:29:08
sfConfig::add(array(
  'mod_shipping_types_enabled' => true,
  'mod_shipping_types_view_class' => 'sfPHP',
));
